# Generated by Django 5.2.13 on 2026-04-18 07:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='contact_number',
            field=models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='Enter a 10-digit phone number using digits only.', regex='^\\d{10}$')]),
        ),
    ]
